backend/api/urls.py
from django.urls import path

from api.views import (
    SearchProductListApiView,
    PortionsListApiView,
    ProductAndPortions,
    BrandProductsList,
    FeedbackCreateApiView,
    ProductComplaintCreateView,
    SlugifierAPIView,
)

app_name = 'api'
urlpatterns = [
    path('feedback/', FeedbackCreateApiView.as_view(), name='feedback'),
    path('products/search/', SearchProductListApiView.as_view(), name='search'),
    path('products/create-complaint/', ProductComplaintCreateView.as_view(), name='product_complaint'),
    path('products/brand/<slug:brand_slug>/', BrandProductsList.as_view(), name='brand_products'),
    path('products/<uuid:product>/portions/', PortionsListApiView.as_view(), name='portions_by_id'),
    path('products/<slug:slug>/product-with-portions/', ProductAndPortions.as_view(), name='product_with_portions'),
    path('slugifier/', SlugifierAPIView.as_view(), name='slugifier'),
]

backend/product_catalog/urls.py
from django.urls import path, include

from product_catalog.views import (
    IndexPage,
    ProductPage,
    BrandPage,
    SearchProduct,
    ProductComplaintCreate,
    FeedBackView,
)

app_name = 'catalog'
urlpatterns = [
    path('', IndexPage.as_view(), name='index'),
    path('search/', SearchProduct.as_view(), name='search'),
    path('feedback/', FeedBackView.as_view(), name='feedback'),
    path('complaint/<slug:product>/', ProductComplaintCreate.as_view(), name='complaint_create'),
    path('brand/<slug:brand>/', BrandPage.as_view(), name='brand_detail'),
    path('api/', include('api.urls')),
    path('<slug:product>/', ProductPage.as_view(), name='product_detail'),

]

backend/seo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views
from django.urls import path, include
from django.views.decorators.cache import cache_page

from product_catalog.sitemap import ProductSitemap, BrandSitemap, StaticViewSitemap

sitemaps = {
    'products': ProductSitemap,
    'brand': BrandSitemap,
    'static': StaticViewSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml',
         cache_page(86400)(sitemaps_views.index),
         {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
    path('sitemap-<section>.xml',
         cache_page(86400)(sitemaps_views.sitemap),
         {'sitemaps': sitemaps}, name='sitemaps'),
    path('', include('product_catalog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/product_catalog/models.py
import uuid as uuid

from django.db import models
from django.urls import reverse


class ProductBrand(models.Model):
    name = models.CharField('Название', max_length=250)
    slug = models.CharField('Машинное название', max_length=200, unique=True)

    def get_url(self):
        return reverse('catalog:brand_detail', kwargs={'brand': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производитель'


class Product(models.Model):
    uuid = models.UUIDField('uid', unique=True, default=uuid.uuid4)
    name = models.CharField('Название', max_length=300, db_index=True)
    slug = models.CharField('Машинное название', max_length=200, unique=True)
    brand = models.ForeignKey(ProductBrand, on_delete=models.CASCADE, null=True, blank=True,
                              related_name='products')

    def get_url(self):
        return reverse('catalog:product_detail', kwargs={'product': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class ProductPortion(models.Model):
    name = models.CharField('Название', max_length=250)
    for_weighing = models.BooleanField('Продукт доступен для взвешивания', default=False)
    calories = models.DecimalField('Калории', decimal_places=2, max_digits=5)
    fat = models.DecimalField('Жиры', decimal_places=2, max_digits=5)
    protein = models.DecimalField('Белки', decimal_places=2, max_digits=5)
    carbohydrates = models.DecimalField('Углеводы', decimal_places=2, max_digits=5)
    xe_count = models.DecimalField('Количество хлебных единиц', decimal_places=2, max_digits=5)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='portions')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Порция продукта'
        verbose_name_plural = 'Порции продуктов'


class TopProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='top_products')
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name = 'Продукт для главной'
        verbose_name_plural = 'Топ продуктов для главной'


class TopBrand(models.Model):
    brand = models.ForeignKey(ProductBrand, on_delete=models.CASCADE, related_name='top_brands')
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.brand.name

    class Meta:
        verbose_name = 'Бренд для главной'
        verbose_name_plural = 'Бренды для главной'


class ProductComplaint(models.Model):
    product = models.ForeignKey(Product, verbose_name='Продукт', on_delete=models.CASCADE,
                                related_name='complaints')
    portion = models.ForeignKey(ProductPortion, verbose_name='Порция', on_delete=models.CASCADE)
    text = models.TextField('Текст жалобы')
    solved = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Жалоба на продукт'
        verbose_name_plural = 'Жалобы на продукты'


class Feedback(models.Model):
    contacts = models.CharField('Контакты', max_length=300)
    text = models.TextField('Текст', max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

backend/product_catalog/forms.py
from django import forms

from product_catalog.models import Feedback


class ProductCompliantForm(forms.Form):
    portion = forms.ChoiceField(label='Порция')
    text = forms.CharField(widget=forms.Textarea, label='Описание проблемы', required=True)

    def __init__(self, *args, **kwargs):
        product = kwargs.pop('product')
        super().__init__(*args, **kwargs)

        portions_choices = product.portions.all().values_list('id', 'name')
        self.fields['portion'].choices = [(str(portion[0]), portion[1]) for portion in portions_choices]

    class Meta:
        fields = ['portion', 'text']


class FeedBackForm(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = ['contacts', 'text']

backend/product_catalog/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.postgres.search import SearchVector
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, DetailView, View, FormView, CreateView, ListView

from product_catalog.forms import ProductCompliantForm, FeedBackForm
from product_catalog.models import TopProduct, TopBrand, Product, ProductBrand, ProductPortion, \
    ProductComplaint


class IndexPage(TemplateView):
    template_name = 'index.html'

    def _get_top_products(self):
        result = []
        product_tops = TopProduct.objects.filter(
            active=True
        ).select_related(
            'product'
        ).only(
            'product__name',
            'product__slug'
        )
        for product_top in product_tops:
            result.append({
                'name': product_top.product.name,
                'url': product_top.product.get_url()
            })
        return result

    def _get_top_brands(self):
        result = []
        top_brands = TopBrand.objects.filter(
            active=True
        ).select_related(
            'brand'
        ).only(
            'brand__name',
            'brand__slug'
        )
        for top_brand in top_brands:
            result.append({
                'name': top_brand.brand.name,
                'url': top_brand.brand.get_url()
            })
        return result

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['top_products'] = self._get_top_products()
        ctx['top_brands'] = self._get_top_brands()
        return ctx


class ProductPage(DetailView):
    template_name = 'product_detail.html'
    queryset = Product.objects.all()
    slug_url_kwarg = 'product'
    context_object_name = 'product'


class BrandPage(ListView):
    template_name = 'brand_detail.html'
    queryset = Product.objects.all()
    context_object_name = 'products'
    paginate_by = 50

    def get_queryset(self):
        self.brand = get_object_or_404(ProductBrand, slug=self.kwargs['brand'])
        return self.queryset.filter(brand=self.brand).order_by('-name')

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super(BrandPage, self).get_context_data(object_list=object_list, **kwargs)
        ctx['brand'] = self.brand
        return ctx


class SearchProduct(View):

    def get(self, request, *args, **kwargs):
        name = request.GET.get('q')
        products = []
        if name and len(name) >= 3:

            qs = (
                Product.objects
                .annotate(search=SearchVector('name', 'brand__name'))
                .filter(search=name)
                .select_related('brand')
                .only('name', 'slug', 'brand__name')
                .order_by('-brand')
                [:settings.PRODUCT_MAX_COUNT_FOR_SEARCH]
            )

            for product in qs:
                if product.brand:
                    name = f'{product.name} ({product.brand.name})'
                else:
                    name = product.name
                products.append({'name': name, 'url': product.get_url()})
        return JsonResponse({'result': products})


class ProductComplaintCreate(FormView):
    template_name = 'product_complaint.html'
    form_class = ProductCompliantForm
    product = None

    def get_product(self):
        return get_object_or_404(Product, slug=self.kwargs.get('product'))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        self.product = self.get_product()
        kwargs['product'] = self.product
        return kwargs

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['product'] = self.product
        return ctx

    def form_valid(self, form):
        portion = get_object_or_404(ProductPortion, id=form.cleaned_data['portion'])
        ProductComplaint.objects.create(product=self.product, portion=portion, text=form.cleaned_data['text'])
        messages.add_message(self.request, messages.INFO, 'Ваше обращение отправлено.')
        return HttpResponseRedirect(self.product.get_url())


class FeedBackView(CreateView):
    template_name = 'feedback.html'
    form_class = FeedBackForm

    def form_valid(self, form):
        form.save()
        messages.add_message(self.request, messages.INFO, 'Ваше обращение отправлено.')
        return HttpResponseRedirect('/')

backend/product_catalog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>{% block title %}{% endblock %}</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="{% block description %}{% endblock %}">

    <link href="{% static 'bootstrap3/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/ct-paper.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/xe_calc.css' %}" rel="stylesheet"/>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'fav/favicon-16x16.png' %}">
    <link rel="icon" href="{% static 'fav/favicon-32x32.png' %}" type="image/x-icon">
    <link rel="manifest" href="{% static 'fav/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'fav/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!--     Fonts and icons     -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>

        <!-- Yandex.RTB -->
    <script>window.yaContextCb=window.yaContextCb||[]</script>
    <script src="https://yandex.ru/ads/system/context.js" async></script>
</head>
<body>
<div id="navbar-full">
    <nav class="navbar navbar-ct-danger" role="navigation-demo">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">XeCalc</a>
            </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
            <ul class="nav navbar-nav navbar-right">
              <li class="nav navbar-nav">
                    <a href="{% url 'catalog:feedback' %}" class="btn btn-danger btn-fill">Остались вопросы?</a>
              </li>
            </ul>
        </div><!-- /.container-->
    </nav>
</div>
<div id="notifications">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %}">
                <div class="container">
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>
<div class="main">
        <div class="container">
            <div class="row">
                {% block banner %}
                    <div class="col-lg-12 text-center margin-top-2">
                        <!-- Yandex.RTB R-A-783138-1 -->
                        <div id="yandex_rtb_R-A-783138-1"></div>
                        <script>window.yaContextCb.push(()=>{
                          Ya.Context.AdvManager.render({
                            renderTo: 'yandex_rtb_R-A-783138-1',
                            blockId: 'R-A-783138-1'
                          })
                        })</script>
                    </div>
                {% endblock %}
            </div>
        </div>
        {% block content %}
        {% endblock %}
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center margin-top-2">
                    <a href="https://play.google.com/store/apps/details?id=com.ivan_kazionov.xecalc">
                        <img width="199" height="77" class="image-fluid" src="{% static 'google-play-badge.png' %}" alt="https://play.google.com/store/apps/details?id=com.ivan_kazionov.xecalc">
                    </a>
                    <a href="https://vk.com/xecalc">
                        <img width="50" height="50" class="image-fluid" src="{% static 'vk_logo.png' %}" alt="https://vk.com/xecalc">
                    </a>
                    <a href="https://t.me/xecalc">
                        <img width="50" height="50" class="image-fluid" src="{% static 'telegram_logo.png' %}" alt="https://t.me/xecalc">
                    </a>
                </div>
            </div>
        </div>
</div>


</body>

    <script src="{% static 'js/jquery-1.10.2.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/jquery-ui-1.10.4.custom.min.js' %}" type="text/javascript"></script>

	<script src="{% static 'bootstrap3/js/bootstrap.js' %}" type="text/javascript"></script>

	<!--  Plugins -->
	<script src="{% static 'js/ct-paper-checkbox.js' %}"></script>
	<script src="{% static 'js/ct-paper-radio.js' %}"></script>
	<script src="{% static 'js/bootstrap-select.js' %}"></script>
	<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

	<script src="{% static 'js/ct-paper.js' %}"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-9Z3NYKEZN0"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-9Z3NYKEZN0');
    </script>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
       (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
       m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
       (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

       ym(70433236, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true,
            webvisor:true
       });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/70433236" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
    {% block bottom_js %}
    {% endblock %}
</html>

backend/product_catalog/templates/brand_detail.html
{% extends 'base.html' %}
{% block title %}Продукты бренда {{ brand.name }}{% endblock %}
{% block description %}{{ brand.name }}: содержание калорий. углеводов, жиров, и хлебных единиц{% endblock %}
{% block content %}
    <div class="section section-nude">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Главная</a></li>
                            <li class="breadcrumb-item active" aria-current="page">{{ brand.name }}</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <h1>Продукты бренда "{{ brand.name }}" с содержанием хлебных единиц</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <table class="table">
                        <tbody>
                            {% for product in products %}
                                <tr>
                                    <td><a href="{{ product.get_url }}">{{ product.name }}</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            {% if paginator.num_pages > 1 %}
                <div class="row">
                    <div class="col-lg-12">
                        <nav>
                            <ul class="pagination">
                                {% for page_num in paginator.page_range %}
                                    {% if page_obj.number == page_num %}
                                        <li class="page-item active">
                                          <a class="page-link" href="#">{{ page_num }} <span class="sr-only">(current)</span></a>
                                        </li>
                                    {% else %}
                                        <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                    {% endif %}
                                {% endfor %}
                           </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

backend/product_catalog/templates/feedback.html
{% extends 'base.html' %}
{% block title %}Обратная связь{% endblock %}
{% block description %}Вопросы и обращения{% endblock %}
{% block content %}
    <div class="section section-nude">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Главная</a></li>
                        <li class="breadcrumb-item active">Обратная связь</li>
                      </ol>
                    </nav>
                </div>
            </div>
            <div class="row margin-top">
                <div class="col-lg-12">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="contacts">Ваши контакты</label>
                            <input type="text" class="form-control" name="contacts" id="contacts">
                            {% for error in form.contacts.errors %}
                                <div class="invalid-feedback">
                                  {{ error|escape }}
                                </div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="text">Ваш вопрос</label>
                            <textarea class="form-control" id="text" name="text" rows="3">{% if form.text.value %}{{ form.text.value }}{% endif %}</textarea>
                            {% for error in form.text.errors %}
                                <div class="invalid-feedback">
                                  {{ error|escape }}
                                </div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

backend/product_catalog/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Содержание хлебных единиц в продуктах{% endblock %}
{% block description %}Продукты питания - хлебные единицы, белки, жиры и углеводы{% endblock %}
{% block content %}
<div class="section">
    <div class="container tim-container">
        <div class="row">
            <div class="col-lg-12">
                <div class="tim-title">
                    <h1>Продукты с содержнием хлебных единиц</h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 ">
                <div class="form-group search">
                    <input name="search" type="text" placeholder="Введите название продукта" class="form-control">
                </div>
            </div>
        </div>
        <div class="row margin-top-2">
            <div class="col-lg-12" id="product_res"></div>
        </div>
        {% if top_products %}
            <div class="row margin-top-2">
                <div class="col-lg-12">
                    <h2>Последние найденые продукты</h2>
                    {% for product in top_products %}
                        <a href="{{ product.url }}" class="label label-primary">{{ product.name }}</a>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        {% if top_brands %}
            <div class="row margin-top-2">
                <div class="col-lg-12">
                    <h2>Бренды</h2>
                    {% for brand in top_brands %}
                        <a href="{{ brand.url }}" class="label label-success">{{ brand.name }}</a>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block bottom_js %}
    <script src="{% static 'js/index.js' %}"></script>
{% endblock %}

backend/product_catalog/templates/product_complaint.html
{% extends 'base.html' %}
{% block title %}Ошибка в {{ product.name }}{% endblock %}
{% block description %}{{ product.name }} неправильные данные{% endblock %}
{% block content %}
    <div class="section section-nude">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Главная</a></li>
                        {% if product.brand %}
                            <li class="breadcrumb-item"><a href="{{ product.brand.get_url }}">{{ product.brand.name }}</a></li>
                        {% endif %}
                        <li class="breadcrumb-item"><a href="{{ product.get_url }}">{{ product.name }}</a></li>
                        <li class="breadcrumb-item active">Жалоба</li>
                      </ol>
                    </nav>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <h1>Опишите проблему связанную с продуктом</h1>
                </div>
            </div>
            <div class="row margin-top">
                <div class="col-lg-12">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="portion">Порция</label>
                            <select class="form-control" id="portion" name="portion">
                                {% for id, value in form.portion.field.choices %}
                                    <option value="{{ id }}"{% if form.portion.value == id %} selected{% endif %}>{{ value }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="text">Описание проблемы</label>
                            <textarea class="form-control is-invalid" id="text" name="text" rows="3">{% if form.text.value %}{{ form.text.value }}{% endif %}</textarea>
                            {% for error in form.text.errors %}
                                <div class="invalid-feedback">
                                  {{ error|escape }}
                                </div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

backend/product_catalog/templates/product_detail.html
{% extends 'base.html' %}
{% block title %}{{ product.name }}{% if product.brand %} ({{ product.brand.name }}){% endif %} - содержание хлебных единиц{% endblock %}
{% block description %}{{ product.name }}{% if product.brand %} ({{ product.brand.name }}){% endif %}: белки, жиры, углеводы и калории{% endblock %}
{% block content %}
    <div class="section section-nude">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Главная</a></li>
                        {% if product.brand %}
                            <li class="breadcrumb-item"><a href="{{ product.brand.get_url }}">{{ product.brand.name }}</a></li>
                        {% endif %}
                        <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
                      </ol>
                    </nav>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <h1>{{ product.name }} - содержание хлебных единиц</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Порция</th>
                                <th scope="col">Калории</th>
                                <th scope="col">Жиры г.</th>
                                <th scope="col">Белки г.</th>
                                <th scope="col">Углеводы г.</th>
                                <th scope="col">Хлебные единицы</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for portion in product.portions.all %}
                                <tr>
                                    <td>{{ portion.name }}</td>
                                    <td>{{ portion.calories|stringformat:'d' }}</td>
                                    <td>{{ portion.fat }}</td>
                                    <td>{{ portion.protein }}</td>
                                    <td>{{ portion.carbohydrates }}</td>
                                    <td><b>{{ portion.xe_count }}</b></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row margin-top">
                <div class="col-lg-12">
                    <p>Расчет хлебных единиц произведен из расчета <b>1 хлебная единица = 12 грамм углеводов</b>.</p>
                    <br>
                    <p class="font-bold">Будьте внимательны, информация о продуктах взята из открытых источников,
                        возможны отклонения от реальных значений, если вы нашли ошибку напишите об этом <a href="{% url 'catalog:complaint_create' product.slug %}">здесь.</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}